/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, post } from '@/lib/api/client';
import type { Message, NewMessage } from '@/types/api-generated';

/**
 * Get all messages (newest first)
 * GET /api/v1/messages
 */
export async function getMessages(): Promise<Message[]> {
  return get<Message[]>('/api/v1/messages');
}

/**
 * Create a new message
 * POST /api/v1/messages
 */
export async function createMessage(data: NewMessage): Promise<Message> {
  return post<Message>('/api/v1/messages', data);
}
